#!/usr/bin/env python3
"""Check declared asm branch targets against the retail disassembly.

quality_scan.py lets a registered library asm routine branch to another
function only when the target is listed in its registry entry's
"branch_targets". This script proves each declaration from retail data: the
retail routine (build/GC6E01/asm/**/*.s, generated by dtk from the original
binary) must branch to exactly the declared functions, no more and no fewer.

It needs a local build with the retail disc extracted. Without the
disassembly it prints a note and exits 0, so CI without retail data is not
blocked; the full link's SHA-1 check still proves the bytes.

usage: verify_asm_branch_targets.py [ASM_DIR]
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY = REPO_ROOT / "docs" / "asm_evidence" / "registry.json"

FN_START = re.compile(r"^\.fn\s+([^,\s]+)")
FN_END = re.compile(r"^\.endfn\s+(\S+)")
LABEL = re.compile(r"^([.\w$@]+):")
BRANCH = re.compile(
    r"^\s*/\*[^*]*\*/\s*(?:b|beq|bne|blt|bgt|ble|bge|bdnz|bdz)[-+]?\s+"
    r"(?:cr\d\s*,\s*)?([A-Za-z_.][\w$@.]*)\s*$"
)


def retail_external_branches(asm_dir: Path) -> dict[str, set[str]]:
    """Map each retail function to the other functions its branches target."""
    result: dict[str, set[str]] = {}
    for path in asm_dir.rglob("*.s"):
        current = None
        labels: set[str] = set()
        targets: list[str] = []
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            start = FN_START.match(line)
            if start:
                current, labels, targets = start.group(1), set(), []
                continue
            if current is None:
                continue
            label = LABEL.match(line)
            if label:
                labels.add(label.group(1))
            branch = BRANCH.match(line)
            if branch:
                targets.append(branch.group(1))
            if FN_END.match(line):
                result[current] = {
                    t for t in targets
                    if t not in labels and not t.startswith(".L") and t != current
                }
                current = None
    return result


def strip_address(name: str) -> str:
    """dtk names some statics `name_XXXXXXXX`; compare on the base name too."""
    return re.sub(r"_[0-9A-Fa-f]{8}$", "", name)


def main() -> int:
    asm_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO_ROOT / "build" / "GC6E01" / "asm"
    entries = json.loads(REGISTRY.read_text(encoding="utf-8")).get("entries", [])
    declared = [e for e in entries if e.get("branch_targets")]
    if not declared:
        print("No registry entries declare branch_targets.")
        return 0
    if not asm_dir.is_dir():
        print(f"note: {asm_dir} not found; retail branch targets not verified (needs a local build).")
        return 0
    retail = retail_external_branches(asm_dir)
    fail = False
    for entry in declared:
        func = entry["function"]
        names = [func, entry.get("address", "")]
        found = next((retail[n] for n in names if n and n in retail), None)
        if found is None:
            print(f"::error::{func}: not found in the retail disassembly under {asm_dir}")
            fail = True
            continue
        want = set(entry["branch_targets"])
        have = set(found)
        if {strip_address(t) for t in want} != {strip_address(t) for t in have} and want != have:
            print(f"::error::{func}: declared branch targets {sorted(want)} != retail {sorted(have)}")
            fail = True
        else:
            print(f"{func}: branch targets {sorted(want)} match retail")
    return int(fail)


if __name__ == "__main__":
    sys.exit(main())
